name: Versatile PyInstaller

on:
  push:
    tags:
      - v*
jobs:
  pyinstaller-windows-build:
    runs-on: windows-latest
    steps:
      - name: Create Windows Executable
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          python_ver: '3.13'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'cleancredits_windows'
          options: --onedir, --name "cleancredits", --windowed,
  pyinstaller-ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          python_ver: '3.13'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'cleancredits_linux'
          options: --onedir, --name "cleancredits", --windowed, 
  pyinstaller-mac-latest-build:
    runs-on: macos-latest
    steps:
      - name: Create Mac Executable
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          python_ver: '3.13'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'cleancredits_macos_arm64'
          options: --onedir, --name "cleancredits", --windowed,
  pyinstaller-mac-13-build:
    runs-on: macos-13
    steps:
      - name: Create Mac Executable
        uses: sayyid5416/pyinstaller@v1.8.0
        with:
          python_ver: '3.13'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'cleancredits_macos_intel'
          options: --onedir, --name "cleancredits", --windowed,
  upload_assets:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Upload assets
        uses: softprops/action-gh-release@v2x
        with:
          files: |
            cleancredits_windows
            cleancredits_linux
            cleancredits_macos_arm64
            cleancredits_macos_intel
